apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-go-chart.fullname" . }}
  labels:
    {{- include "hello-go-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default 8081 }}
      protocol: TCP
      name: http
  selector:
    {{- include "hello-go-chart.selectorLabels" . | nindent 4 }}
