apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi-pod
          image: fastapi-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /live
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: POD_NAME
              #value name should be the same as the metadata name of the deployed pod with the ending hashes
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: GREETING
              valueFrom:
                configMapKeyRef:
                  name: fastapi-cm
                  key: GREETING
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fastapi-secret
                  key: DB_PASSWORD
      imagePullSecrets:
        - name: regcred
